name: Run Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data preprocessing
        run: |
          python -m your_data_processing_script  # Adjust this to your actual script

      - name: Run tests
        run: |
          python -m unittest discover -s tests
